### PR TITLE
9 implement search bar for homepage

### LINKED ISSUE #9: Implement Search Bar for Homepage
### Summary

Implement a search bar on the homepage to allow users to input search queries. This task focuses on designing and integrating the search bar into the homepage layout.

### Tasks

- Design the search bar component.
- Integrate the search bar into the homepage layout.
- Style the search bar to match the overall theme of the application.

### Acceptance Criteria

- The search bar is prominently displayed on the homepage.
- The search bar is responsive and looks good on different screen sizes.

### Additional Notes

- Ensure the search bar is accessible and provides a good user experience.
- Placeholder text for the search bar can be "Search for products..."

### PR DESCRIPTION
**Pull request by FrancoisLunick**
### Summary
Implemented a search bar on the homepage to allow users to input search queries. This task involved designing, integrating, and styling the search bar within the navigation bar.

### Changes Made
- Added a `SearchBar` component that includes a category dropdown, search input field, and search button.
- Integrated the `SearchBar` component into the `NavigationBar` component for better UI consistency.
- Styled the search bar to match the overall theme of the application and ensured it is responsive.
- Adjusted the `NavigationBar` CSS to accommodate the search bar and maintain a clean layout.

### Acceptance Criteria
- The search bar is prominently displayed on the homepage.
- The search bar is responsive and looks good on different screen sizes.

### Additional Notes
- The search bar is designed to provide a good user experience.
- Placeholder text for the search bar is "Search Amazon".

### CODE REVIEW

**Review by Cybersunami — CHANGES_REQUESTED** [review]
The color of the navigation bar seems slightly off from the original website, and the search bar appears a tad too wide in size. For future reference, If you inspect the elements on the Amazon website it will show you the colors and sizes.

**Review by Cybersunami — CHANGES_REQUESTED** [review]
The sizing still seems a bit off. I provided you with images for the exact sizing of the search bar.

Screenshot 2024-07-07 at 8 01 11 PM

Screenshot 2024-07-07 at 8 03 03 PM

**Comment by FrancoisLunick** [comment]
It seems like the actual size is different from your screenshot.
Screenshot 2024-07-07 at 20 25 17

**Review by Cybersunami — CHANGES_REQUESTED** [review]
I see. The px amount varies between screen sizes. Instead, try using root em. it will make the sizes more responsive to different screen sizes.

**Comment by FrancoisLunick** [comment]
> I see. The px amount varies between screen sizes. Instead, try using root em. it will make the sizes more responsive to different screen sizes.

I made the changes.

**Review by Cybersunami — APPROVED** [review]
The sizing isn’t exactly what I hoped for but overall great job!

**Pull request merged**
